version: '3.8'

services:
  # Money Manager Application
  money-manager:
    build: .
    container_name: money-manager-app
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose directly for your nginx to proxy
    environment:
      # Salt Edge Configuration
      - SALTEDGE_BASE_URL=${SALTEDGE_BASE_URL:-https://www.saltedge.com/api/v6}
      - SALTEDGE_APP_ID=${SALTEDGE_APP_ID}
      - SALTEDGE_SECRET_KEY=${SALTEDGE_SECRET_KEY}
      - SALTEDGE_CLIENT_ID=${SALTEDGE_CLIENT_ID}
      
      # Database Configuration
      - DATABASE_URL=sqlite:////app/data/money_manager.db
      
      # Google API Configuration (optional)
      - GOOGLE_CREDENTIALS_FILE=${GOOGLE_CREDENTIALS_FILE:-/app/credentials/credentials.json}
      - GOOGLE_TOKEN_FILE=${GOOGLE_TOKEN_FILE:-/app/credentials/token.json}
      
      # Application Configuration
      - DEBUG=${DEBUG:-False}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      # Persistent database storage
      - ./data:/app/data
      # Google API credentials (if using Google Docs)
      - ./credentials:/app/credentials:ro
      # Logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Database backup service
  backup:
    image: alpine:latest
    container_name: money-manager-backup
    restart: unless-stopped
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    environment:
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-0 2 * * *}  # Daily at 2 AM
    command: >
      sh -c "
        apk add --no-cache dcron &&
        echo '${BACKUP_SCHEDULE:-0 2 * * *} cp /data/money_manager.db /backups/money_manager_$$(date +\"%Y%m%d_%H%M%S\").db && find /backups -name \"money_manager_*.db\" -mtime +30 -delete' | crontab - &&
        crond -f
      "
    profiles:
      - backup
