from sqlalchemy import Column, Integer, String, DateTime, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .base import Base

class Customer(Base):
    """Customer model based on Salt Edge API customer structure."""
    
    __tablename__ = "customers"
    
    id = Column(Integer, primary_key=True, index=True)
    saltedge_customer_id = Column(String, unique=True, index=True, nullable=False)
    identifier = Column(String, unique=True, index=True, nullable=False)  # Your internal customer ID
    secret = Column(String, nullable=False)  # Generated by Salt Edge
    
    # Additional fields for your application
    email = Column(String, index=True)
    first_name = Column(String)
    last_name = Column(String)
    phone = Column(String)
    
    # Metadata
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())
    
    # Relationships
    connections = relationship("Connection", back_populates="customer", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Customer(id={self.id}, identifier='{self.identifier}', email='{self.email}')>"
